import React, { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/banner";
import BannerSmallAnnouncement from "../components/banner-small-announcement";
import Footer from "../components/footer";
import LatestArrivals from "../components/latest-arrivals";
import MarqueeBrands from "../components/marque-brands";
import MarqueeBrands2 from "../components/marque-brands-2";
import MostViewed from "../components/most-viewed";
import WebNav from "../components/web-nav";
import Categories from "../components/categories";
import AboutSection from "../components/about";

const Home: NextPage = () => {
  const [offsetY, setOffsetY] = useState<number>(0);
  const handleScroll = (): void => {
    if (offsetY > 1600) return;
    setOffsetY(window.pageYOffset);
  };

  useEffect(() => {
    // if(offsetY > 1637) setOffsetY(1637);
  }, [offsetY]);

  useEffect(() => {
    document.addEventListener("scroll", handleScroll);

    return () => document.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div className="main-wrapper">
      <Head>
        <title>Techpal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width initial-scale=1 minimum-scale=1 maximum-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />

        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" /> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700"
          rel="stylesheet"
        />
      </Head>

      <div className="header-container w-full h-full sticky top-0 -z-10">
        <WebNav />
        <BannerSmallAnnouncement />
        <Banner />
      </div>

      <div className="parralax-container h-full w-full z-10">
        <div className="padded-content-container h-full w-full px-0 sm:px-32 2xl:px-64 bg-white flex flex-col items-center">
          <LatestArrivals />
          
          <div className="h-[calc(50vh-4.75rem)] flex flex-col justify-center items-center">
            <h3 className="text-xl font-semibold text-slate-700 mb-5">
              Available brands
            </h3>
            <MarqueeBrands />
            <MarqueeBrands2 />
          </div>

          <div className="spacer h-20 w-full bg-white"></div>
          <MostViewed />
          <div className="spacer h-20 w-full bg-white"></div>
          {/* <Categories /> */}
        </div>
        {/* <div className="spacer h-24 w-full bg-white"></div> */}

        <AboutSection />
        <Footer />
      </div>


    </div>
  );
};

export default Home;
